# Generated by Django 3.2.4 on 2021-07-22 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_productito', models.CharField(max_length=50, verbose_name='Producto')),
                ('costo', models.IntegerField(verbose_name='Costo')),
                ('stock', models.IntegerField(default=0, verbose_name='Stock')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripcion Producto')),
            ],
        ),
    ]
