# Generated by Django 3.2.3 on 2021-07-02 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=50, verbose_name='Nombre Producto')),
                ('precio_producto', models.IntegerField(verbose_name='Precio Producto')),
                ('stock_producto', models.IntegerField(default=0, verbose_name='Stock del producto')),
                ('fecha_creacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de creación')),
            ],
        ),
    ]
